[package]
name = "chip8"
version = "0.1.0"
authors = ["Andrew Bass <andybass009@gmail.com>"]
build = "build.rs"

[dependencies]
rand = "*"

[dependencies.sdl2]
git = "https://github.com/Rust-SDL2/rust-sdl2"
